<!-- Habitat content -->
<h1>Blue Whale Habitat</h1>

<img src = "<?=base_url();?>images/bonney_upwelling.jpg" class="floatRight">
<p>Blue whales are drawn to the region by the Bonney Upwelling (and surrounding upwelling areas), which starts around the start of November each year, driven by south-east winds. The upwelling brings vast quantities of nutrients from the deep Southern Ocean into shallow coastal waters of the continental shelf (less than 200m deep). Upwelled nutrients combine with sunlight to stimulate blooms of phytoplankton, minute plants that provide food for krill and small fish. Krill live in the upwelling year round, but their numbers increase when abundant food is available during the upwelling season and their swarms get bigger throughout the season. Reflecting this, blue whales arrive at the start of the upwelling season to start feeding, and many remain until May. </p>
<br />
<p>The Blue Whale Study is studying blue whale habitat at different scales. Our ‘broad-scale’ aerial survey program has searched for whales over a huge area between Bass Strait and the Bight, enabling us to correlate our sightings with a range of habitat variables. These include depth, distance from land, distance from the 200m shelf break, sea surface temperature (SST), and sea surface chlorophyll (SSC). Our habitat modeling has shown that SST is the most important habitat feature, followed by SSC and depth. It is not clear yet exactly what this means, and we are planning further modeling using additional explanatory variables. But it is clear that blue whales tend to gather along the edge of the Bonney Upwelling surface plume, where the cold nutrient-rich water has been warmed by the sun and by warmer offshore water, and where krill gather in dense swarms. Elsewhere the picture is not so clear, as upwelling does not reach the surface in many areas and vessel surveys are needed to verify what is happening below the surface. </p>
<br />
<p>Our small boat surveys are taking a different perspective, homing in on ‘fine-scale’ areas to examine where krill occur in the water column, and what type of prey is targeted by blue whales. To do this we carry out surveys in which we search for krill with our scientific depth sounder, pausing at regular intervals to lower our CTD, a probe that measures temperature at various depths (a critical factor in krill distribution), while constantly searching for blue whales. When we find whales we may switch into ‘focal follow’ mode, leaving our survey track to see what the whales do and where they take us - often they take us to the densest krill swarms around! In 2007 for the first time we used suction-cup dive loggers, that attach to the whales and record their dive depth and 3-dimensional underwater movements, which can be related to krill swarms and the surrounding environment. While we still have a way to go with this difficult work, we already have some fascinating data that is shedding light on the mysterious underwater world of blue whales and krill.  </p>
